env:
    es2021: true
    node: true
parser: '@typescript-eslint/parser'
parserOptions:
    ecmaVersion: 2021
    sourceType: module
extends:
    - eslint:recommended
    - plugin:@typescript-eslint/recommended
    - prettier
plugins:
    - import
rules:
    no-unused-vars:
        - warn
        - argsIgnorePattern: ^_
          caughtErrorsIgnorePattern: ^_
